#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/usr/bin/dunst &

# Kill polybar
polybar-msg cmd quit
killall -q polybar
while pgrep  -u $UID -x polybar > /dev/null; do sleep 1; done

# Set xrandr
~/.config/xrandr/xrandr_reset

m_count=$(xrandr -q | grep -wc connected)
pri="eDP-1-1"
gpu_mode=$(optimus-manager --print-mode | awk '{print $5}')
if [[ $gpu_mode == "integrated" ]]; then
    pri="eDP-1"
fi
if [[ $m_count == 2 ]]; then
    sec=$(xrandr -q | grep -w connected | grep -v $pri | awk '{print $1}')
    bspc monitor $pri -d ₁ ₂ ₃ ₄ ₅
    bspc monitor $sec -d ₆ ₇ ₈ ₉ ₀
else
    bspc config remove_disabled_monitors true
    bspc config remove_unplugged_monitors true
    bspc monitor $pri -d ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉ ₀
fi

~/.fehbg &
picom --config ~/.config/picom/picom.conf -b

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=floating
bspc rule -a Wine state=floating
bspc rule -a netease-cloud-music state=floating
bspc rule -a Font-manager state=floating
bspc rule -a obs state=floating
bspc rule -a matplotlib state=floating rectangle=1280x720+320+160
bspc rule -a org.remmina.Remmina state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a weixin state=floating
bspc rule -a rdesktop state=floating

# Input method
pgrep -x fcitx5 > /dev/null || fcitx5 &

# Polybar
~/.config/polybar/launch.sh

